"""added_timestamps

Revision ID: f6f60c3d5988
Revises: 8a1f1e35b0a9
Create Date: 2026-05-15 10:15:44.577576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f60c3d5988'
down_revision: Union[str, Sequence[str], None] = '8a1f1e35b0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('buses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('favorites', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('routes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('schedules', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('schedules', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('schedules', 'updated_at')
    op.drop_column('schedules', 'created_at')
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_column('favorites', 'updated_at')
    op.drop_column('buses', 'updated_at')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
